### ISSUE TITLE
Does not handle JSON secrets

### ISSUE THREAD

**Issue by ncsibra** [jonasvinther/medusa#47]
We have a secret in a kv2 engine that has a big JSON object as data.
Exporting this secret with medusa works fine, both in yaml and json format, but when importing back, it tries to create separate secrets from every key/value pair instead of creating just one secret with the whole JSON object.
Plus during this try, it's unable to handle some keys with this error: `Error while writing secret. json: unsupported type: importer.RawYaml`.

**Comment by jonasvinther** [comment]
Hi @ncsibra 

I just tested this, and you are totally right that if you export as json it will mess up everything. I hadn't thought about that scenario. But I just tried to export using the yaml format and it looks like yaml is handling json values more nicely. Can you try and export and import using yaml?

This is my export result when using `--format="json"`:
`A:
  B:
    json-example: |-
      {
                "Da": "value 1",
                "Db": {
                  "DBa": 13,
                  "DBb": "value 2"
                }
              }`

**Comment by ncsibra** [comment]
Hi @jonasvinther,

I tried before, but now tried again and it does not work.  
Sample json created under "medusa" kv2 secret engine and "cake" secret name through vault GUI:
```
{
  "id": "0001",
  "type": "donut",
  "name": "Cake",
  "ppu": 0.55,
  "batters": {
    "batter": [
      {
        "id": "1001",
        "type": "Regular"
      },
      {
        "id": "1002",
        "type": "Chocolate"
      },
      {
        "id": "1003",
        "type": "Blueberry"
      },
      {
        "id": "1004",
        "type": "Devil's Food"
      }
    ]
  },
  "topping": [
    {
      "id": "5001",
      "type": "None"
    },
    {
      "id": "5002",
      "type": "Glazed"
    },
    {
      "id": "5005",
      "type": "Sugar"
    },
    {
      "id": "5007",
      "type": "Powdered Sugar"
    },
    {
      "id": "5006",
      "type": "Chocolate with Sprinkles"
    },
    {
      "id": "5003",
      "type": "Chocolate"
    },
    {
      "id": "5004",
      "type": "Maple"
    }
  ]
}
```

Export: `medusa export medusa --format="yaml" -o ~/tmp/test.yml`
Result:
```
cake:
  batters:
    batter:
    - id: "1001"
      type: Regular
    - id: "1002"
      type: Chocolate
    - id: "1003"
      type: Blueberry
    - id: "1004"
      type: Devil's Food
  id: "0001"
  name: Cake
  ppu: 0.55
  topping:
  - id: "5001"
    type: None
  - id: "5002"
    type: Glazed
  - id: "5005"
    type: Sugar
  - id: "5007"
    type: Powdered Sugar
  - id: "5006"
    type: Chocolate with Sprinkles
  - id: "5003"
    type: Chocolate
  - id: "5004"
    type: Maple
  type: donut
```

Import: 
```
➜  ~ medusa import medusa ~/tmp/test.yml
Error while writing secret. json: unsupported type: importer.RawYaml
Error while writing secret. json: unsupported type: importer.RawYaml
```
In this case does not import anything to vault.

#### Environment

Arch Linux under WSL2.

Vault: 1.5.4.
Medusa: 0.2.2. (amd64)
Go: go1.15.8 (linux/amd64)
